// authReduser
export const AUTH_SUCSESSFULLY = 'AUTH_SUCSESSFULLY';
export const LOGOUT = 'LOGOUT';
export const ADD_NOTEBOOK = 'ADD_NOTEBOOK';
export const ADD_NOTE = 'ADD_NOTE';
export const INIT_NOTEBOOK = 'INIT_NOTEBOOK';
export const SELECT_ACTIVE_NOTEBOOK = 'SELECT_ACTIVE_NOTEBOOK';
export const DELETE_NOTEBOOK = 'DELETE_NOTEBOOK';
export const DELETE_NOTE = 'DELETE_NOTE';
